language: go
go:
- 1.7.3
before_install:
- go get github.com/mitchellh/gox
script:
- gox
deploy:
  provider: releases
  api_key:
    secure: fYfZZtv7SpVKLUaOrWFWqH/zCG65qrPSUtgh0RHMmV6jYOZAIgq4mQRGF6167T7Atiw7yq4hFK27j1fAfuQnuD8Dr1gJKViQfpylN59OgKmgDbq1fHavTd53Tm2usk2laYp0QJ0b9oeyE6s82dPjigDmnGa41qmWRQE10sJ81OE+heeCnMIq+JBdI5FaTczpo1G65KabGPR/xSKwwn34SeyKjTNCnqjiHUF8M+ywp2u8b/DnkGPaxoFwwEwMyuNrkWerKTwnggKYZA+WUur5QB9VwdzXuyREYgSlaV90oW4taw7QFV70zbtFGxWb6/KHkPqGJrtUx2Cit+eZeQ8rZGGHMf8NFNyZBqgs3G2QWWMITUPD7oddwlZVUk/UOsnems9psfvN1XBEhvIu7WCLagRRFoBKs9gS4Rb6HLe/13FoxucoED3eQP04KYsd2CTxPtIpWpJSL9KM1y2/CsczMXEQGJLlQ3fhoddMDzPffd3lp5hBtpNlkdILoY1CJIaLnW0WYsdH/hVpQDoSFYNzmI3DuVTU/3Jud63r+NdMpZTP2+kXddsMF86EBopabt8/fCpMveKPY9Dm5rtUGazJ99aV6JJbI4stTm437moo1fxr9SJb4mHSODYn3FoNzzsl3RpByPSBYZd7wv1tEtjeNLyso4OumogIDqlFVL7Td4E=
  file:
    - noip_netbsd_arm
    - noip_freebsd_amd64
    - noip_darwin_386
    - noip_darwin_amd64
    - noip_linux_386
    - noip_linux_amd64
    - noip_linux_arm
    - noip_freebsd_386
    - noip_windows_amd64.exe
    - noip_openbsd_386
    - noip_openbsd_amd64
    - noip_windows_386.exe
    - noip_netbsd_386
    - noip_freebsd_arm
    - noip_netbsd_amd64
  on:
    repo: pdxjohnny/noip
  skip_cleanup: true
