language: go
go:
- 1.7.3
before_install:
- go get github.com/mitchellh/gox
script:
- gox
deploy:
  provider: releases
  api_key:
    secure: s7RQhZ+v2FZ9vNhVon5r1kafahWKBRm9zri4B2a03ZzInWtpTivdjVEGGowU+6CQYranliBpCxroaiXLuqAukGdi6HTR178SbPNw5In+cdAPo5u2eUvMiYgDNraXchklDWRzmpP+Pxle8TC7BPEcV0/mVsXHF6iwgWHhWRtOoXXl5SGsyrkMCytml1ZhW/IIfmF6zjKuFGq+tnVE6QxPTrb7MrInYXP8OgVnOImB5daq0l2YV+FAyJyaTD2z5lnXlQYaE68xBCFEYvVdE/v6k8or/Xzi02yffyGikdhUuwxpEWLXJXl7gY8KBP9T+/iWbEbTFHTzls6k2ur5PBTHvYJqUV+mqsZ0Ko+3xmnRnWapXecKBawdAlsJJblpO9ItAOKGxjF3BoQh9GWmwrLt+wvHloclarFjErvpOEOm9SFrWbY5g50JgCWEP1w5ZMd71JtiuOR6Wtk9ovkS8QL0Pe+i1pWywQNduflTeCWqU4BfRaLZg1AOSjSZcvh+tPuu45koxoCdiP0v5XaewTooN9Q7MAqCWa9z9CndYS15FGMN+J4II5sRv+JkpuJEKhqDJE0oa8/c3jkXBj1bVqsA6Tuj20seLukDpbaciDEP8wqq2ZKXhfHKVWH9D+UJq803JHacL843lNZpFbrZPZXkSvJj9c7/PjiHpGvTrU4MfGI=
  file:
    - noip_netbsd_arm
    - noip_freebsd_amd64
    - noip_darwin_386
    - noip_darwin_amd64
    - noip_linux_386
    - noip_linux_amd64
    - noip_linux_arm
    - noip_freebsd_386
    - noip_windows_amd64.exe
    - noip_openbsd_386
    - noip_openbsd_amd64
    - noip_windows_386.exe
    - noip_netbsd_386
    - noip_freebsd_arm
    - noip_netbsd_amd64
  on:
    repo: pdxjohnny/noip
  skip_cleanup: true
